---
- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    name: "*"
    state: latest

- name: Install some packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - glances
    - htop
